version: 0.2
phases:
  install:
      runtime-versions:
        java: openjdk11
      commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn clean compile test
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - 'appspec.yml'
    - 'target/petclinic.war'
    - 'scripts/*'
